#!/usr/bin/env bash

export BCH_CRON__root=$(dirname $(dirname ${BASH_SOURCE[0]}))

. $(dirname ${BASH_SOURCE[0]})/lib/__init__.sh BCH_CRON

for pth in $(ls ${BCH_CRON__root}/.bch.bin/bch.cron*); do
    [ ! -f $pth ] && continue
    :::link::: $pth
done
