#!/usr/bin/env bash

export BCH_CRON__root=$(dirname $(dirname ${BASH_SOURCE[0]}))

. $(dirname ${BASH_SOURCE[0]})/lib/__init__.sh BCH_CRON

for pth in $(ls $(dirname ${BASH_SOURCE[0]})/bin/bch.*); do
    [ ! -f $pth ] && continue
    :::link::: $pth
done
